# Generated by Django 5.0.3 on 2024-06-10 18:06

import django.db.models.deletion
import taxi_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True,
                 validators=[taxi_app.models.validate_future_date])),
                ('name', models.TextField(max_length=200)),
                ('phone', models.TextField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Aggregator',
                'verbose_name_plural': 'Aggregators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxiDriver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=20)),
                ('car', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Taxi Driver',
                'verbose_name_plural': 'Taxi Drivers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True,
                 validators=[taxi_app.models.validate_future_date])),
                ('name', models.TextField(max_length=200)),
                ('date', models.DateTimeField(validators=[
                 taxi_app.models.validate_future_date])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_address', models.TextField(max_length=250)),
                ('destination_address', models.TextField(max_length=250)),
                ('taxi_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='orders', to='taxi_app.taxidriver')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TaxiDriverAggregator',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='taxi_app.aggregator')),
                ('taxi_driver', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='taxi_app.taxidriver')),
            ],
            options={
                'verbose_name': 'Taxi Driver Aggregator Relationship',
                'verbose_name_plural': 'Taxi Driver Aggregator Relationships',
                'ordering': ['aggregator', 'taxi_driver'],
                'unique_together': {('taxi_driver', 'aggregator')},
            },
        ),
        migrations.AddField(
            model_name='taxidriver',
            name='aggregators',
            field=models.ManyToManyField(
                through='taxi_app.TaxiDriverAggregator', to='taxi_app.aggregator'),
        ),
        migrations.AddField(
            model_name='aggregator',
            name='taxi_drivers',
            field=models.ManyToManyField(
                through='taxi_app.TaxiDriverAggregator', to='taxi_app.taxidriver'),
        ),
    ]
