name: Check
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 taxi/ taxi_app/

  tests:
    name: Тесты
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: taxi_app_db
        ports:
        - 5458:5432
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
        pip install numpy
        pip install django
        pip install python-dotenv
        pip install djangorestframework
        pip install psycopg2-binary
    - name: Tests
      env:
        PG_HOST: 127.0.0.1
        PG_PORT: 5458
        PG_USER: user
        PG_PASSWORD: password
        PG_DBNAME: taxi_app_db
      run: |
        ./manage.py test